import {
  TrainingType,
  ExerciseStatus,
  SkillLevel,
  EntityState,
  TrainingExercise,
} from "@prisma/client";

export const trainingExercises: TrainingExercise[] = [
  {
    id: "1",
    label: "Basic Forehand Drive",
    duration: 90,
    practiceInstruction: "Focus on consistent contact and follow-through.",
    type: TrainingType.technique,
    status: ExerciseStatus.PUBLISHED,
    repsInstruction: "3 x 10",
    coachNotes: "Emphasize brushing contact",
    intensityScore: 2,
    skillLevel: SkillLevel.BEGINNER,
    entityState: EntityState.CREATED,
    createdAt: new Date(),
    updatedAt: new Date(),
    mainVideoId: null,
    previewVideoId: null,
    thumbnail: "",
  },
  {
    id: "2",
    label: "Backhand Block Drill",
    duration: 60,
    practiceInstruction: "Block forehand loops to your backhand.",
    type: TrainingType.rally,
    status: ExerciseStatus.PUBLISHED,
    repsInstruction: "2 x 8",
    coachNotes: "Stay low and balanced",
    intensityScore: 3,
    skillLevel: SkillLevel.INTERMEDIATE,
    entityState: EntityState.CREATED,
    createdAt: new Date(),
    updatedAt: new Date(),
    mainVideoId: null,
    previewVideoId: null,
    thumbnail: "",
  },
  {
    id: "3",
    label: "Serve to Short Forehand",
    duration: 45,
    practiceInstruction: "Use backspin serves short to forehand.",
    type: TrainingType.serve,
    status: ExerciseStatus.DRAFT,
    repsInstruction: "5 x 5",
    coachNotes: "Watch elbow and wrist",
    intensityScore: 2,
    skillLevel: SkillLevel.BEGINNER,
    entityState: EntityState.CREATED,
    createdAt: new Date(),
    updatedAt: new Date(),
    mainVideoId: null,
    previewVideoId: null,
    thumbnail: "",
  },
  {
    id: "4",
    label: "Serve & Step Out",
    duration: 75,
    practiceInstruction: "Serve and pivot for a 3rd ball forehand.",
    type: TrainingType.return,
    status: ExerciseStatus.PUBLISHED,
    repsInstruction: "3 x 6",
    coachNotes: "Explode with legs",
    intensityScore: 4,
    skillLevel: SkillLevel.INTERMEDIATE,
    entityState: EntityState.CREATED,
    createdAt: new Date(),
    updatedAt: new Date(),
    mainVideoId: null,
    previewVideoId: null,
    thumbnail: "",
  },
  {
    id: "5",
    label: "Forehand Footwork Circle",
    duration: 60,
    practiceInstruction: "Move around cone with forehand drive.",
    type: TrainingType.footwork,
    status: ExerciseStatus.PUBLISHED,
    repsInstruction: "4 x 6",
    coachNotes: "Quick recovery step",
    intensityScore: 5,
    skillLevel: SkillLevel.ADVANCED,
    entityState: EntityState.CREATED,
    createdAt: new Date(),
    updatedAt: new Date(),
    mainVideoId: null,
    previewVideoId: null,
    thumbnail: "",
  },

  // 15 more exercises (you can duplicate or slightly vary these)
  ...Array.from({ length: 15 }, (_, i) => ({
    id: (6 + i).toString(),
    label: `Drill ${i + 6}`,
    duration: 45 + (i % 5) * 15,
    practiceInstruction: `Perform drill variation ${i + 1}`,
    type: Object.values(TrainingType)[i % Object.values(TrainingType).length],
    status: i % 3 === 0 ? ExerciseStatus.PUBLISHED : ExerciseStatus.DRAFT,
    repsInstruction: `${2 + (i % 3)} x ${5 + (i % 4)}`,
    coachNotes: `Note for drill ${i + 6}`,
    intensityScore: 1 + (i % 5),
    skillLevel: [
      SkillLevel.BEGINNER,
      SkillLevel.INTERMEDIATE,
      SkillLevel.ADVANCED,
    ][i % 3],
    entityState: EntityState.CREATED,
    createdAt: new Date(),
    updatedAt: new Date(),
    mainVideoId: null,
    previewVideoId: null,
    thumbnail: "",
  })),
];
